// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	"github.com/gogf/gf/os/gtime"
)

// Role is the golang structure for table role.
type Role struct {
	Id        uint64      `orm:"id,primary" json:"id"`        //
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //
	DeletedAt *gtime.Time `orm:"deleted_at" json:"deletedAt"` //
	Name      string      `orm:"name"       json:"name"`      //
}

// Task is the golang structure for table task.
type Task struct {
	Id        uint64      `orm:"id,primary" json:"id"`        //
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //
	DeletedAt *gtime.Time `orm:"deleted_at" json:"deletedAt"` //
	Title     string      `orm:"title"      json:"title"`     //
	Done      int         `orm:"done"       json:"done"`      //
}

// User is the golang structure for table user.
type User struct {
	Id        uint64      `orm:"id,primary" json:"id"`        //
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //
	DeletedAt *gtime.Time `orm:"deleted_at" json:"deletedAt"` //
	Username  string      `orm:"username"   json:"username"`  //
	Password  string      `orm:"password"   json:"password"`  //
	Avatar    string      `orm:"avatar"     json:"avatar"`    //
}

// UserRole is the golang structure for table user_role.
type UserRole struct {
	UserId uint64 `orm:"user_id,primary" json:"userId"` //
	RoleId uint64 `orm:"role_id,primary" json:"roleId"` //
}
