// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"goframe_learn/app/model/internal"
)

// Roles is the golang structure for table roles.
type Roles internal.Roles

// Fill with you ideas below.