// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"goframe_template/app/model/internal"
)

// Role is the golang structure for table role.
type Role internal.Role

// Fill with you ideas below.
type RoleApiRequest struct {
	Name string `orm:"name"       json:"name"` //
}
type RoleApiResponse struct {
	Id   uint64 `orm:"id,primary" json:"id"`   //
	Name string `orm:"name"       json:"name"` //
}
