// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"goframe_learn/app/model/internal"
)

// Task is the golang structure for table task.
type Task internal.Task

// Fill with you ideas below.
