// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"goframe_learn/app/model/internal"
)

// Users is the golang structure for table users.
type Users internal.Users

// Fill with you ideas below.