// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"goframe_learn/app/model/internal"
)

// UserRole is the golang structure for table user_role.
type UserRole internal.UserRole

// Fill with you ideas below.