// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// Role is the golang structure for table role.
type Role struct {
    Id        uint64      `orm:"id,primary" json:"id"`        //   
    CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //   
    UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //   
    DeletedAt *gtime.Time `orm:"deleted_at" json:"deletedAt"` //   
    Name      string      `orm:"name"       json:"name"`      //   
}