// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Task is the golang structure for table task.
type Task struct {
	Id        uint64      `orm:"id,primary" json:"id"`        //
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //
	DeletedAt *gtime.Time `orm:"deleted_at" json:"deletedAt"` //
	Title     string      `orm:"title"      json:"title"`     //
	Done      int         `orm:"done"       json:"done"`      //
}
