// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// UserRole is the golang structure for table user_role.
type UserRole struct {
    UserId uint64 `orm:"user_id,primary" json:"userId"` //   
    RoleId uint64 `orm:"role_id,primary" json:"roleId"` //   
}