// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"goframe_learn/app/dao/internal"
)

// rolesDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type rolesDao struct {
	*internal.RolesDao
}

var (
	// Roles is globally public accessible object for table roles operations.
	Roles = &rolesDao{
		internal.Roles,
	}
)

// Fill with you ideas below.